#!/bin/bash


while read -r GenomeLine; do
echo $GenomeLine
	export speciesCode=`echo "$GenomeLine" | awk -F',' '{print $2}'`
	export filename=./OriginalGenomes/$speciesCode'_genomeAssembly.fna'
	sed -i -e 's/-/_/g' $filename
	sed -i -e 's/(/_/g' $filename
	sed -i -e 's/)/_/g' $filename

mkdir EditedGenomes

mv $filename EditedGenomes

done <GenomeList.txt